### ISSUE TITLE
Turning the Choro Songbook into machine readable format file like .musicxml?

### ISSUE THREAD

**Issue by felixCheungcheung** [DCMLab/choro#1]
Dear Willian and  Fabian,

I am Huicheng Zhang, a master's student in Music Technology Group, Universitat Pompeu Fabra. I am quite interested in Brazilian Choro music. In order to promote more computational research on choro music, did you guys consider building a symbolic dataset out of Choro Songbook using optical music recognition technique? Although we can study the chord symbols and formal structures, melody and rhythmic information is missing in the current choro.tsv. We can not uncover the essence and beauty of choro unless we know all the note information. I wonder if you have plans in this direction?

Regards,
Huicheng Zhang

**Comment by fabianmoss** [comment]
It's more appropriate to discuss this per email. I'll send you a message soon.
